from collections.abc import Sequence
from types import TracebackType
from typing import Any, Self

class Error(Exception): ...
class InterfaceError(Error): ...
class DatabaseError(Error): ...
class OperationalError(DatabaseError): ...

class Cursor:
    def execute(self, query: str, params: Sequence[object] | None = ...) -> None: ...
    def fetchall(self) -> list[dict[str, Any]]: ...
    def close(self) -> None: ...

class Connection:
    def cursor(self, as_dict: bool = ...) -> Cursor: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

def connect(
    server: str = ...,
    user: str = ...,
    password: str = ...,
    database: str = ...,
    timeout: int = ...,
    login_timeout: int = ...,
) -> Connection: ...
